### PR TITLE
Major Changes Made

### PR DESCRIPTION
**Pull request by AndrewNQN**
1) Finished CreateCard Use Case. Edited documentation and completed presenter

2) Created EditQuiz Use Case with all documentation and implementation completed.

3) Changes to FlashCardFactory to remove select all card

4) Added an additional helper method in Quiz entity

5) Minor changes to view state and additional variables in ViewModel

For anyone reviewing, please be thorough with this one as a lot of changes were made

### CODE REVIEW

**Review by aldob02 — APPROVED** [review]
Looks good to me, didn't notice any issues.

**Review by aldob02 — COMMENTED** [review]
Actually after thinking about it, what would happen if the quiz we want to edit doesn't exist? Or would it be impossible to do so while using the program?

**Comment by AndrewNQN** [comment]
Thank you Aldo for finding that mistake!

**Review by aldob02 — APPROVED** [review]
OK, looks good to me now

**Comment by AlbertYS** [comment]
Good changes, will fix alot of things

**Review by jakan9 — APPROVED** [review]
Looks great!

**Review by AlbertYS — APPROVED** [review]
Looks good, will fix alot of things

**Pull request merged**
