### PR TITLE
Aldo export deck

### PR DESCRIPTION
**Pull request by aldob02**
Implementation and Testing for the deck exporting use case.

This use case writes the name and cards of a deck to a file. Creates a new file if none exists, and overwrites the file if it does exist.

### CODE REVIEW

**Review by AlbertYS — APPROVED** [review]
Looks great

**Review by derrickcho3715 — APPROVED** [review]
This looks good. All the proper documentation is there and it has all the necessary files. Don't forget to add tests for export deck.

**Review by tsoisze2 — DISMISSED** [review]
The changes look great and have all inheritance correctly stated.

**Comment by AndrewNQN** [comment]
Good refactoring to adhere to clean architecture. Few changes may be needed to implement a fail view.

**Review by JamieJChew — APPROVED** [review]
Looks good. Code is structured well and not too difficult to read, only thing I'd point out though is that you might want to break up the interactor's exportDeck method into some helper methods so it isn't too clunky.

**Review by AlbertYS — APPROVED** [review]
Good code, good documentation, make sure public things are public and private things are private

**Review by jakan9 — APPROVED** [review]
Looks good!

**Pull request merged**
