### PR TITLE
Jasmine delete quiz

### PR DESCRIPTION
**Pull request by tsoisze2**

### CODE REVIEW

**Comment by tsoisze2** [comment]
- Created the delete quiz use case with documentation and presenter.
- Added ERROR to ViewStates

**Review by AndrewNQN — APPROVED** [review]
Everything looks good. However, to make code easier to read, you could change the view model creation to multiple lines similar to delete deck presenter. But that is not important right now.

**Review by JamieJChew — APPROVED** [review]
Looks good to me; it's neat and clean. Only thing I would say is what Andrew said so yeah gj.

**Review by aldob02 — APPROVED** [review]
looks good, follows clean architecture and our naming conventions

**Pull request merged**
