### PR TITLE
Aldo import deck

### PR DESCRIPTION
**Pull request by aldob02**
Implementation and Testing for the deck importing use case.

This use case reads a file and creates a deck containing cards if the file contents are formatted correctly. Otherwise, it will create an empty deck.

### CODE REVIEW

**Review by AlbertYS — APPROVED** [review]
Looks great, make sure to keep documenting the code and creating tests

**Review by JamieJChew — APPROVED** [review]
Looks good. Nice work having docstrings for your methods and it looks like your code follows clean architecture fairly well. 

Only things would be that you might want to move some of your code from your interactors' importDeck() and exportDeck() methods to some helper methods to make them a bit less bloat-y. And it looks like you have a test class for importDeck but also don't forget about exportDeck if you're not already working on it.

gj

**Review by jakan9 — APPROVED** [review]
All the methods seem to be properly documented as to what their function is. All changes also seem to follow clean architecture that is simple to understand. The only suggestion that I would give is to include a little bit more documentation on the filetype and structure of the exported files. It would make it easy to understand what the user/developer would expect if they opened this file and needed to make changes to it.

**Review by jakan9 — APPROVED** [review]

**Review by JamieJChew — APPROVED** [review]
Looks good. Nice work having docstrings for your methods and it looks like your code follows clean architecture fairly well.

Only things would be that you might want to move some of your code from your interactors' importDeck() and exportDeck() methods to some helper methods to make them a bit less bloat-y. And it looks like you have a test class for importDeck but also don't forget about exportDeck if you're not already working on it.

gj

**Review by jakan9 — APPROVED** [review]
All the methods seem to be properly documented as to what their function is. All changes also seem to follow clean architecture that is simple to understand. The only suggestion that I would give is to include a little bit more documentation on the filetype and structure of the exported files. It would make it easy to understand what the user/developer would expect if they opened this file and needed to make changes to it.

**Review by JamieJChew — COMMENTED** [review]
Looks good. Nice work having docstrings for your methods and it looks like your code follows clean architecture fairly well.

Something you'll probably need to change is that I don't the outputData object should contain an actual Deck object, but rather a deckName String. This is because the controller and the view shouldn't have access to Deck objects because that would violate clean architecture.

I think once that's done it should be good for merging.

**Review by jakan9 — APPROVED** [review]

**Review by JamieJChew — DISMISSED** [review]
I like it, good implementation and documentation. 👍

**Review by AlbertYS — DISMISSED** [review]
This feature has been implemented extensively, nice documentation

**Comment by aldob02** [comment]
Sorry guys had to fix conflicts!

**Review by JamieJChew — APPROVED** [review]
looks good

**Review by jakan9 — APPROVED** [review]
Looks good!

**Review by tsoisze2 — APPROVED** [review]
looks good to me

**Pull request merged**
