### PR TITLE
Jamie run quiz

### PR DESCRIPTION
**Pull request by JamieJChew**
This has the updated methods for our view design. The controller methods are now void and the presenter creates ViewModels to be passed to the view.

### CODE REVIEW

**Review by AlbertYS — DISMISSED** [review]
Good documentation, nice clean implementation

**Review by aldob02 — APPROVED** [review]
nice work on documentation and testing

**Review by jakan9 — APPROVED** [review]
Code looks good. Great work with documentation and removing blank lines as well.

**Review by tsoisze2 — APPROVED** [review]
Good

**Pull request merged**
