### PR TITLE
Card Screen DONE! [Not really but almost :)]

### PR DESCRIPTION
**Pull request by AndrewNQN**
I did my best to refactor CardScreen and I do think it is much cleaner and easy to understand now. Last step will be to add comments. Additionally, the screen has been changed to keep the color choices consistent throughout the program.

### CODE REVIEW

**Review by tsoisze2 — APPROVED** [review]
I think adding blank lines and other formatting does make the code easier to read which is good. CardScreen looks very long to me. Maybe we can shorten this class a little bit by moving the methods to another class.

**Comment by AndrewNQN** [comment]
Deck Screen changes have also been added to this pull request

**Review by aldob02 — APPROVED** [review]
I like the refactoring done on CardScreen, much easier to read and follow. Everything else looks good as well.

**Review by jakan9 — APPROVED** [review]
Good work and thinking with the refactoring.

**Review by JamieJChew — APPROVED** [review]
I like the refactoring, specifically how you added private helper methods to make the code a little less clunky. It looks a lot neater now and easier to read. gj

**Pull request merged**
